export const LocalTempleData = [
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 2,
        "festival_end_time": "November 6",
        "festival_start_time": "November 5",
        "id": 1,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 13-14",
        "name": "Parassinikadavu Sri Muthappan Temple",
        "phone": null,
        "place": "Parassinikadavu",
        "popularity": 5,
        "theyyams": []
    },
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 9,
        "festival_end_time": "November 15",
        "festival_start_time": "November 7",
        "id": 2,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 21-29",
        "name": "Madikai Erikkulam Padinharchamundi Kshethram",
        "phone": null,
        "place": "Erikkulam",
        "popularity": 4,
        "theyyams": []
    },
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 4,
        "festival_end_time": "November 10",
        "festival_start_time": "November 7",
        "id": 3,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 17-20",
        "name": "Kottiyoor Nanmadam Temple",
        "phone": null,
        "place": "Kottiyoor",
        "popularity": 4,
        "theyyams": []
    },
    {
     	"address":"", 
     	"created_at":"2024-11-06 05:41:27", 
     	"festival_duration_days" :2, 
     	"festival_end_time":"November 28", 
     	"festival_start_time":"November 27", 
     	"id" :5, 
     	"images":[] , 
     	"img" :null, 
     	"location" :null, 
     	"malayala_masam":"Vrischikam 11-12", 
     	"name":"Narikkode Sree Puthiya Kunnath Puthiya Bhagavathi Kshethram", 
     	"phone" :null, 
     	"place":"Ezhome", 
     	"popularity" :3, 
     	"theyyams":[]
    },
    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"November 8", 
    	"festival_start_time":"November 6", 
    	"id" :6, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 15-16", 
    	"name":"Sree Kuruvappalli Ara Devaswom", 
    	"phone" :null, 
    	"place":"Kannur", 
    	"popularity" :4, 
    	"theyyams":[]
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :2, 
    	"festival_end_time":"November 7", 
    	"festival_start_time":"November 6", 
    	"id" :8, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 21-22",  
    	"name":"Pilicode Sree Rayaramangalam Vishnumurthy Temple",  
    	"phone" :null,  
    	"place":"Pilicode",  
    	"popularity ":3,  
    	"theyyams":[]
    },
    {
    	"address":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Kuttamath_poomala_bhagavathy_temple_Cheruvathur_02.jpg/1200px-Kuttamath_poomala_bhagavathy_temple_Cheruvathur_02.jpg", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"November 9", 
    	"festival_start_time":"November 7", 
    	"id" :9, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 21-23",  
    	"name":"Cheruvathur Kuttamath Ponmalam Sri Vishnumurthy Temple",  
    	"phone" :null,  
    	"place":"Kuttamath",  
    	"popularity ":3,  
    	"theyyams":[]
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :4, 
    	"festival_end_time":"December 25", 
    	"festival_start_time":"December 22", 
    	"id" :10, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"",  
    	"name":"Erikkulam Sree Vettakkorumakan Temple",  
    	"phone" :null,  
    	"place":"Madikkai",  
    	"popularity ":2,  
    	"theyyams":['Vettakkorumakan','Muchilottu Bhagavathy']
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"April 30", 
    	"festival_start_time":"April 28", 
    	"id" :11, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"",  
    	"name":"Thimiri kottumburam Dharmasastha Chamundeswari Kshethram",  
    	"phone" :null,  
    	"place":"Kasargod, Cheruvathur, Palathera, Thimiri",  
    	"popularity ":4,  
    	"theyyams":[]
    },
]
