export const LocalTempleData = [
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 2,
        "festival_end_time": "November 6",
        "festival_start_time": "November 5",
        "id": 1,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 13-14",
        "name": "Parassinikadavu Sri Muthappan Temple",
        "phone": null,
        "place": "Parassinikadavu",
        "popularity": 5,
        "theyyams": []
    },
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 9,
        "festival_end_time": "November 15",
        "festival_start_time": "November 7",
        "id": 2,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 21-29",
        "name": "Madikai Erikkulam Padinharchamundi Kshethram",
        "phone": null,
        "place": "Erikkulam",
        "popularity": 4,
        "theyyams": []
    },
    {
        "address": "",
        "created_at": "2024-11-06 05:41:27",
        "festival_duration_days": 4,
        "festival_end_time": "November 10",
        "festival_start_time": "November 7",
        "id": 3,
        "images": [],
        "img": null,
        "location": null,
        "malayala_masam": "Thulam 17-20",
        "name": "Kottiyoor Nanmadam Temple",
        "phone": null,
        "place": "Kottiyoor",
        "popularity": 4,
        "theyyams": []
    },
    {
     	"address":"", 
     	"created_at":"2024-11-06 05:41:27", 
     	"festival_duration_days" :2, 
     	"festival_end_time":"November 28", 
     	"festival_start_time":"November 27", 
     	"id" :5, 
     	"images":[] , 
     	"img" :null, 
     	"location" :null, 
     	"malayala_masam":"Vrischikam 11-12", 
     	"name":"Narikkode Sree Puthiya Kunnath Puthiya Bhagavathi Kshethram", 
     	"phone" :null, 
     	"place":"Ezhome", 
     	"popularity" :3, 
     	"theyyams":[]
    },
    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"November 8", 
    	"festival_start_time":"November 6", 
    	"id" :6, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 15-16", 
    	"name":"Sree Kuruvappalli Ara Devaswom", 
    	"phone" :null, 
    	"place":"Kannur", 
    	"popularity" :4, 
    	"theyyams":[]
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :2, 
    	"festival_end_time":"November 7", 
    	"festival_start_time":"November 6", 
    	"id" :8, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 21-22",  
    	"name":"Pilicode Sree Rayaramangalam Vishnumurthy Temple",  
    	"phone" :null,  
    	"place":"Pilicode",  
    	"popularity ":3,  
    	"theyyams":[]
    },
    {
    	"address":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Kuttamath_poomala_bhagavathy_temple_Cheruvathur_02.jpg/1200px-Kuttamath_poomala_bhagavathy_temple_Cheruvathur_02.jpg", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"November 9", 
    	"festival_start_time":"November 7", 
    	"id" :9, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Thulam 21-23",  
    	"name":"Cheruvathur Kuttamath Ponmalam Sri Vishnumurthy Temple",  
    	"phone" :null,  
    	"place":"Kuttamath",  
    	"popularity ":3,  
    	"theyyams":[]
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :4, 
    	"festival_end_time":"December 25", 
    	"festival_start_time":"December 22", 
    	"id" :10, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"",  
    	"name":"Erikkulam Sree Vettakkorumakan Temple",  
    	"phone" :null,  
    	"place":"Madikkai",  
    	"popularity ":2,  
    	"theyyams":['Vettakkorumakan']
    },

    {
    	"address":"", 
    	"created_at":"2024-11-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"April 30", 
    	"festival_start_time":"April 28", 
    	"id" :11, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"",  
    	"name":"Thimiri kottumburam Dharmasastha Chamundeswari Kshethram",  
    	"phone" :null,  
    	"place":"Kasargod, Cheruvathur, Palathera, Thimiri",  
    	"popularity ":4,  
    	"theyyams":[]
    },






	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :7, 
    	"festival_end_time":"December  18", 
    	"festival_start_time":"December 11", 
    	"id" :12, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Vrichikam 25 - Dhanu 2",  
    	"name":"Iduvangal Sree Vishnumoorthi Temple",  
    	"phone" :null,  
    	"place":"Irikkur",  
    	"popularity ":3,  
    	"theyyams":['Gulikan','Vishnumoorthi ','Raktheswari']
    },

	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :4, 
    	"festival_end_time":"December  14", 
    	"festival_start_time":"December 11", 
    	"id" :13, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Vrichikam 25-28",  
    	"name":"Kokkad Sree Muchilott Bhagavathi Kshethram",  
    	"phone" :null,  
    	"place":"Cheruthazham",  
    	"popularity ":4,  
    	"theyyams":['Muchilot Bhagavathi','Vishnumoorthi ','Kundor Chamundi','Puliyoor Kannan','Kannagattu Bhagavathi','Narambil Bhagavathi']
    },

	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"December  21", 
    	"festival_start_time":"December 19", 
    	"id" :14, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Dhanu 4,5,6",  
    	"name":"Karippal Nagam Aayillyam Ulsavam",  
    	"phone" :null,  
    	"place":"Eramam",  
    	"popularity ":3,  
    	"theyyams":['Nagakanyaka','Naagarajan']
    },
	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"December  22", 
    	"festival_start_time":"December 20", 
    	"id" :15, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Dhanu 5,6,7",  
    	"name":"Pandyancheri Sri.Bhagavathi Kshethram",  
    	"phone" :null,  
    	"place":"Thalassery",  
    	"popularity ":3,  
    	"theyyams":['Gulikan','Karanavar ','Pothi','Nagabhagavathy','Bhairavan','kuttichathan','bhagavathi','Vishnumoorthi']
    },
	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :2, 
    	"festival_end_time":"December  22", 
    	"festival_start_time":"December 21", 
    	"id" :16, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Dhanu 6,7",  
    	"name":"Sree Pottan Dhaivasthanam Pallikunnumpuram",  
    	"phone" :null,  
    	"place":"Azhikode",  
    	"popularity ":4,  
    	"theyyams":['Pottan Theyyam','Gulikan','Kurathiyamma']
    },
	{
    	"address":"", 
    	"created_at":"2024-12-06 05:41:27", 
    	"festival_duration_days" :3, 
    	"festival_end_time":"December  24", 
    	"festival_start_time":"December 22", 
    	"id" :17, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Dhanu 7,8,9",  
    	"name":"Sree Vettakkorumakan Kshethram,Kannom",  
    	"phone" :null,  
    	"place":"Ezhom",  
    	"popularity ":3,  
    	"theyyams":['Vettakkorumakan','Oorpazhassi Daivathaar']
    },




	{
    	"address":"https://travelkannur.com/wp-content/uploads/2016/05/mundya1-730x428.jpg", 
    	"created_at":"2024-12-30 05:41:27", 
    	"festival_duration_days" :11, 
    	"festival_end_time":"May 15", 
    	"festival_start_time":"May 4", 
    	"id" :18, 
    	"images":[] , 
    	"img" :null, 
    	"location" :null, 
    	"malayala_masam":"Medam 21-Edavam 1",  
    	"name":"Cheemeni Sree Vishnumurthy Kshetram",  
    	"phone" :null,  
    	"place":"Kasargod-Cheemeni",  
    	"popularity ":5,  
    	"theyyams":['Vishnumoorthi','Raktha Chamundi']
    },
]
